### ISSUE TITLE
在 Lumen 5.4 下安装不成功

### ISSUE THREAD

**Issue by yyqqing** [lsxiao/jwt-auth#1]

**Comment by Sloaix** [comment]
有错误日志吗？@yyqqing

**Comment by yyqqing** [comment]
Using version ^1.0 for lsxiao/jwt-auth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install lsxiao/jwt-auth v1.0.4
    - Conclusion: don't install lsxiao/jwt-auth v1.0.3
    - Conclusion: don't install lsxiao/jwt-auth v1.0.2
    - Conclusion: don't install lsxiao/jwt-auth v1.0.1
    - Conclusion: don't install lsxiao/jwt-auth v1.0
    - Conclusion: remove illuminate/auth v5.4.9
    - Installation request for lsxiao/jwt-auth ^1.0 -> satisfiable by lsxiao/jwt-auth[v1.0, v1.0.1, v1.0.1-alpha, v1.0.2, v1.0.3, v1.0.4].
    - Conclusion: don't install illuminate/auth v5.4.9
    - lsxiao/jwt-auth v1.0.1-alpha requires illuminate/auth 5.1.* || 5.2.* || 5.3.* -> satisfiable by illuminate/auth[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - Can only install one of: illuminate/auth[5.1.x-dev, v5.4.9].
    - Can only install one of: illuminate/auth[5.2.x-dev, v5.4.9].
    - Can only install one of: illuminate/auth[5.3.x-dev, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.1, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.13, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.16, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.2, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.20, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.22, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.25, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.28, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.30, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.31, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.41, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.6, v5.4.9].
    - Can only install one of: illuminate/auth[v5.1.8, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.0, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.19, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.21, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.24, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.25, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.26, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.27, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.28, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.31, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.32, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.37, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.43, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.45, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.6, v5.4.9].
    - Can only install one of: illuminate/auth[v5.2.7, v5.4.9].
    - Can only install one of: illuminate/auth[v5.3.0, v5.4.9].
    - Can only install one of: illuminate/auth[v5.3.16, v5.4.9].
    - Can only install one of: illuminate/auth[v5.3.23, v5.4.9].
    - Can only install one of: illuminate/auth[v5.3.4, v5.4.9].
    - Installation request for illuminate/auth (locked at v5.4.9) -> satisfiable by illuminate/auth[v5.4.9].


Installation failed, reverting ./composer.json to its original content.


这是错误信息。我看了下，应该是因为 lsxiao/jwt-auth 的 composer.json 中描述依赖项，使用的是明确版本格式，如 "illuminate/auth": "5.1.* || 5.2.* || 5.3.*", 改为 "illuminate/auth": "~5.*", 应该就可以了。其他几个依赖项也是一样问题

**Comment by Sloaix** [comment]
修复了，已经发布了1.0.5，不过没测试。还是不行的话等这周末我会更新版本，修复些问题。
